In [1]:
import theano.tensor as T
from theano import config, shared
import numpy as np


In [2]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../../'))

from deepensemble.utils.utils_functions import ActivationFunctions
from deepensemble.models.sequential import Sequential
from deepensemble.layers.dense import Dense
from deepensemble.metrics import *
from deepensemble.utils import *

from collections import OrderedDict


In [3]:
A = np.array([[0, 1], [0, 1], [1, 0], [1, 0]], dtype=config.floatX)
B = np.array([[1, 0], [1, 0], [0, 1], [0, 1]], dtype=config.floatX)
C = np.array([[0, 1], [1, 0], [0, 1], [0, 1]], dtype=config.floatX)

In [4]:
s = ITLFunctions.silverman(A)
print('Silverman: %0.4g' % s.eval())

Silverman: 0.3824


In [5]:
diffA = ITLFunctions.get_diff([A])
diffB = ITLFunctions.get_diff([B])
diffC = ITLFunctions.get_diff([C])

In [6]:
diffA[0].shape.eval()

array([4, 4, 2])

In [7]:
KA = ITLFunctions.kernel_gauss_diff(diffA, np.sqrt(2) * s)
KB = ITLFunctions.kernel_gauss_diff(diffB, np.sqrt(2) * s)
KC = ITLFunctions.kernel_gauss_diff(diffC, np.sqrt(2) * s)

In [8]:
dKA = T.squeeze(T.sum(ITLFunctions.get_prod(A, A), axis=-1))
dKB = T.squeeze(T.sum(ITLFunctions.get_prod(A, B), axis=-1))
dKC = T.squeeze(T.sum(ITLFunctions.get_prod(A, C), axis=-1))

In [9]:
KKA = KA * (1. - dKA) 
KKB = KB * (1. - dKB) 
KKC = KC * (1. - dKC) 

In [10]:
KA.eval()

array([[ 0.29432702,  0.29432702,  0.00962862,  0.00962862],
       [ 0.29432702,  0.29432702,  0.00962862,  0.00962862],
       [ 0.00962862,  0.00962862,  0.29432702,  0.29432702],
       [ 0.00962862,  0.00962862,  0.29432702,  0.29432702]])

In [11]:
KKB.eval()

array([[ 0.29432702,  0.29432702,  0.00962862,  0.00962862],
       [ 0.29432702,  0.29432702,  0.00962862,  0.00962862],
       [ 0.00962862,  0.00962862,  0.29432702,  0.29432702],
       [ 0.00962862,  0.00962862,  0.29432702,  0.29432702]])

In [12]:
KC.eval()

array([[ 0.29432702,  0.00962862,  0.29432702,  0.29432702],
       [ 0.00962862,  0.29432702,  0.00962862,  0.00962862],
       [ 0.29432702,  0.00962862,  0.29432702,  0.29432702],
       [ 0.29432702,  0.00962862,  0.29432702,  0.29432702]])

In [17]:
V_nc, V_J, V_M = ITLFunctions.get_cip([A], A, s)
print("V_nc: %.4g, V_J: %.4g, V_M: %.4g" % (V_nc.eval(), V_J.eval(), V_M.eval()))

V_nc: 0.0231, V_J: 0.04336, V_M: 0.0231


In [18]:
V_nc, V_J, V_M = ITLFunctions.get_cip([B], A, s)
print("V_nc: %.4g, V_J: %.4g, V_M: %.4g" % (V_nc.eval(), V_J.eval(), V_M.eval()))

V_nc: 0.0231, V_J: 0.04336, V_M: 0.0231


In [19]:
V_nc, V_J, V_M = ITLFunctions.get_cip([C], A, s)
print("V_nc: %.4g, V_J: %.4g, V_M: %.4g" % (V_nc.eval(), V_J.eval(), V_M.eval()))

V_nc: 0.02851, V_J: 0.03357, V_M: 0.02851
